### ISSUE TITLE
Show all Animals broken

### ISSUE THREAD

**Issue by goreil** [IvanovStepanM/Animals_note#1]
### Description
The option to show all animals is broken

### Steps to reproduce
Test has been done in the IDLE environment

1. Run the main program main.py
2. Enter option 2 - "Show pets"
3. Enter option 7 - "Show all pets"

### Expected Result
It shows all pets.

### Actual Result
It enters an endless loop printing "Just type a number 1-6."

**Comment by IvanovStepanM** [comment]
Thanks a lot!
